server:
  port: 9005

spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_db
    username: telco_admin
    password: telco_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092